export default function getCoinImage(coin) {
  const coin_image = coin + '.png';
  switch (coin_image) {
    case 'act.png':
      return require('./act.png');
    case 'ada.png':
      return require('./ada.png');
    case 'adx.png':
      return require('./adx.png');
    case 'ae.png':
      return require('./ae.png');
    case 'aion.png':
      return require('./aion.png');
    case 'amp.png':
      return require('./amp.png');
    case 'ant.png':
      return require('./ant.png');
    case 'ardr.png':
      return require('./ardr.png');
    case 'ark.png':
      return require('./ark.png');
    case 'atm.png':
      return require('./atm.png');
    case 'bat.png':
      return require('./bat.png');
    case 'bay.png':
      return require('./bay.png');
    case 'bcc.png':
      return require('./bcc.png');
    case 'bch.png':
      return require('./bch.png');
    case 'bcn.png':
      return require('./bcn.png');
    case 'bdl.png':
      return require('./bdl.png');
    case 'bela.png':
      return require('./bela.png');
    case 'blcn.png':
      return require('./blcn.png');
    case 'blk.png':
      return require('./blk.png');
    case 'block.png':
      return require('./block.png');
    case 'bnb.png':
      return require('./bnb.png');
    case 'bnt.png':
      return require('./bnt.png');
    case 'bq.png':
      return require('./bq.png');
    case 'bqx.png':
      return require('./bqx.png');
    case 'btc.png':
      return require('./btc.png');
    case 'btcd.png':
      return require('./btcd.png');
    case 'btcz.png':
      return require('./btcz.png');
    case 'btg.png':
      return require('./btg.png');
    case 'btm.png':
      return require('./btm.png');
    case 'bts.png':
      return require('./bts.png');
    case 'btx.png':
      return require('./btx.png');
    case 'burst.png':
      return require('./burst.png');
    case 'clam.png':
      return require('./clam.png');
    case 'cloak.png':
      return require('./cloak.png');
    case 'cnd.png':
      return require('./cnd.png');
    case 'cnx.png':
      return require('./cnx.png');
    case 'cny.png':
      return require('./cny.png');
    case 'cvc.png':
      return require('./cvc.png');
    case 'dash.png':
      return require('./dash.png');
    case 'data.png':
      return require('./data.png');
    case 'dbc.png':
      return require('./dbc.png');
    case 'dcn.png':
      return require('./dcn.png');
    case 'dcr.png':
      return require('./dcr.png');
    case 'default.png':
      return require('./default.png');
    case 'dent.png':
      return require('./dent.png');
    case 'dgb.png':
      return require('./dgb.png');
    case 'dgd.png':
      return require('./dgd.png');
    case 'doge.png':
      return require('./doge.png');
    case 'drgn.png':
      return require('./drgn.png');
    case 'edg.png':
      return require('./edg.png');
    case 'edoge.png':
      return require('./edoge.png');
    case 'elf.png':
      return require('./elf.png');
    case 'ella.png':
      return require('./ella.png');
    case 'emc.png':
      return require('./emc.png');
    case 'emc2.png':
      return require('./emc2.png');
    case 'eng.png':
      return require('./eng.png');
    case 'eos.png':
      return require('./eos.png');
    case 'etc.png':
      return require('./etc.png');
    case 'eth.png':
      return require('./eth.png');
    case 'ethos.png':
      return require('./ethos.png');
    case 'etn.png':
      return require('./etn.png');
    case 'etp.png':
      return require('./etp.png');
    case 'eur.png':
      return require('./eur.png');
    case 'evx.png':
      return require('./evx.png');
    case 'exmo.png':
      return require('./exmo.png');
    case 'exp.png':
      return require('./exp.png');
    case 'fair.png':
      return require('./fair.png');
    case 'fct.png':
      return require('./fct.png');
    case 'fil.png':
      return require('./fil.png');
    case 'fldc.png':
      return require('./fldc.png');
    case 'flo.png':
      return require('./flo.png');
    case 'fun.png':
      return require('./fun.png');
    case 'game.png':
      return require('./game.png');
    case 'gas.png':
      return require('./gas.png');
    case 'gbp.png':
      return require('./gbp.png');
    case 'gbx.png':
      return require('./gbx.png');
    case 'gbyte.png':
      return require('./gbyte.png');
    case 'gno.png':
      return require('./gno.png');
    case 'gnt.png':
      return require('./gnt.png');
    case 'grc.png':
      return require('./grc.png');
    case 'grs.png':
      return require('./grs.png');
    case 'gup.png':
      return require('./gup.png');
    case 'gxs.png':
      return require('./gxs.png');
    case 'hsr.png':
      return require('./hsr.png');
    case 'huc.png':
      return require('./huc.png');
    case 'hush.png':
      return require('./hush.png');
    case 'icn.png':
      return require('./icn.png');
    case 'icx.png':
      return require('./icx.png');
    case 'index.js':
      return require('./index.js');
    case 'jpy.png':
      return require('./jpy.png');
    case 'kcs.png':
      return require('./kcs.png');
    case 'kin.png':
      return require('./kin.png');
    case 'kmd.png':
      return require('./kmd.png');
    case 'knc.png':
      return require('./knc.png');
    case 'krb.png':
      return require('./krb.png');
    case 'lbc.png':
      return require('./lbc.png');
    case 'link.png':
      return require('./link.png');
    case 'lkk.png':
      return require('./lkk.png');
    case 'lrc.png':
      return require('./lrc.png');
    case 'lsk.png':
      return require('./lsk.png');
    case 'ltc.png':
      return require('./ltc.png');
    case 'maid.png':
      return require('./maid.png');
    case 'mana.png':
      return require('./mana.png');
    case 'mcap.png':
      return require('./mcap.png');
    case 'mco.png':
      return require('./mco.png');
    case 'med.png':
      return require('./med.png');
    case 'miota.png':
      return require('./miota.png');
    case 'mkr.png':
      return require('./mkr.png');
    case 'mln.png':
      return require('./mln.png');
    case 'mnx.png':
      return require('./mnx.png');
    case 'mona.png':
      return require('./mona.png');
    case 'mtl.png':
      return require('./mtl.png');
    case 'music.png':
      return require('./music.png');
    case 'nas.png':
      return require('./nas.png');
    case 'nav.png':
      return require('./nav.png');
    case 'ndz.png':
      return require('./ndz.png');
    case 'nebl.png':
      return require('./nebl.png');
    case 'neo.png':
      return require('./neo.png');
    case 'neos.png':
      return require('./neos.png');
    case 'nlc2.png':
      return require('./nlc2.png');
    case 'nlg.png':
      return require('./nlg.png');
    case 'nmc.png':
      return require('./nmc.png');
    case 'nxs.png':
      return require('./nxs.png');
    case 'nxt.png':
      return require('./nxt.png');
    case 'omg.png':
      return require('./omg.png');
    case 'omni.png':
      return require('./omni.png');
    case 'ost.png':
      return require('./ost.png');
    case 'ox.png':
      return require('./ox.png');
    case 'pac.png':
      return require('./pac.png');
    case 'part.png':
      return require('./part.png');
    case 'pasl.png':
      return require('./pasl.png');
    case 'pay.png':
      return require('./pay.png');
    case 'pink.png':
      return require('./pink.png');
    case 'pirl.png':
      return require('./pirl.png');
    case 'pivx.png':
      return require('./pivx.png');
    case 'poe.png':
      return require('./poe.png');
    case 'pot.png':
      return require('./pot.png');
    case 'powr.png':
      return require('./powr.png');
    case 'ppc.png':
      return require('./ppc.png');
    case 'ppt.png':
      return require('./ppt.png');
    case 'pura.png':
      return require('./pura.png');
    case 'qash.png':
      return require('./qash.png');
    case 'qiwi.png':
      return require('./qiwi.png');
    case 'qlc.png':
      return require('./qlc.png');
    case 'qsp.png':
      return require('./qsp.png');
    case 'qtum.png':
      return require('./qtum.png');
    case 'rads.png':
      return require('./rads.png');
    case 'rcn.png':
      return require('./rcn.png');
    case 'rdd.png':
      return require('./rdd.png');
    case 'rdn.png':
      return require('./rdn.png');
    case 'rep.png':
      return require('./rep.png');
    case 'req.png':
      return require('./req.png');
    case 'rhoc.png':
      return require('./rhoc.png');
    case 'ric.png':
      return require('./ric.png');
    case 'rise.png':
      return require('./rise.png');
    case 'rlc.png':
      return require('./rlc.png');
    case 'rpx.png':
      return require('./rpx.png');
    case 'rub.png':
      return require('./rub.png');
    case 'salt.png':
      return require('./salt.png');
    case 'san.png':
      return require('./san.png');
    case 'sbd.png':
      return require('./sbd.png');
    case 'sberbank.png':
      return require('./sberbank.png');
    case 'sc.png':
      return require('./sc.png');
    case 'sky.png':
      return require('./sky.png');
    case 'smart.png':
      return require('./smart.png');
    case 'sngls.png':
      return require('./sngls.png');
    case 'snt.png':
      return require('./snt.png');
    case 'start.png':
      return require('./start.png');
    case 'steem.png':
      return require('./steem.png');
    case 'storj.png':
      return require('./storj.png');
    case 'storm.png':
      return require('./storm.png');
    case 'strat.png':
      return require('./strat.png');
    case 'sub.png':
      return require('./sub.png');
    case 'sys.png':
      return require('./sys.png');
    case 'taas.png':
      return require('./taas.png');
    case 'tkn.png':
      return require('./tkn.png');
    case 'tnc.png':
      return require('./tnc.png');
    case 'trx.png':
      return require('./trx.png');
    case 'tzc.png':
      return require('./tzc.png');
    case 'ubq.png':
      return require('./ubq.png');
    case 'usd.png':
      return require('./usd.png');
    case 'usdt.png':
      return require('./usdt.png');
    case 'ven.png':
      return require('./ven.png');
    case 'veri.png':
      return require('./veri.png');
    case 'via.png':
      return require('./via.png');
    case 'vivo.png':
      return require('./vivo.png');
    case 'vrc.png':
      return require('./vrc.png');
    case 'vtc.png':
      return require('./vtc.png');
    case 'waves.png':
      return require('./waves.png');
    case 'wax.png':
      return require('./wax.png');
    case 'wtc.png':
      return require('./wtc.png');
    case 'xbc.png':
      return require('./xbc.png');
    case 'xcp.png':
      return require('./xcp.png');
    case 'xdn.png':
      return require('./xdn.png');
    case 'xem.png':
      return require('./xem.png');
    case 'xlm.png':
      return require('./xlm.png');
    case 'xmg.png':
      return require('./xmg.png');
    case 'xmr.png':
      return require('./xmr.png');
    case 'xmy.png':
      return require('./xmy.png');
    case 'xp.png':
      return require('./xp.png');
    case 'xpm.png':
      return require('./xpm.png');
    case 'xrb.png':
      return require('./xrb.png');
    case 'xrp.png':
      return require('./xrp.png');
    case 'xtz.png':
      return require('./xtz.png');
    case 'xuc.png':
      return require('./xuc.png');
    case 'xvc.png':
      return require('./xvc.png');
    case 'xvg.png':
      return require('./xvg.png');
    case 'xzc.png':
      return require('./xzc.png');
    case 'zcl.png':
      return require('./zcl.png');
    case 'zec.png':
      return require('./zec.png');
    case 'zen.png':
      return require('./zen.png');
    case 'zrx.png':
      return require('./zrx.png');
    default:
      return require('./default.png');
  }
}
